# Project configuration
[project]
name = "robust-radiotherapy-planning"
version = "0.1.0"
requires-python = "==3.11.15"
dependencies = [
    "einops>=0.8.2,<1.0.0",
    "jupyter>=1.1.1,<2.0.0",
    "lpips>=0.1.4",
    "matplotlib>=3.10.8,<4.0.0",
    "monai>=1.5.2,<2.0.0",
    "mypy>=1.20.0,<2.0.0",
    "nibabel>=5.4.2,<6.0.0",
    "numpy==2.4.4",
    "optuna>=4.8.0,<5.0.0",
    "pandas>=2.2",
    "ruff>=0.15.9,<1.0.0",
    "scikit-image>=0.26.0,<1.0.0",
    "simpleitk>=2.5.3,<3.0.0",
    "torch>=2.11.0,<3.0.0",
    "torchvision>=0.26.0,<1.0.0",
    "tqdm>=4.67.3,<5.0.0",
]

# Allow for optionally installing the GPU version of PyTorch
[project.optional-dependencies]
gpu = [
    "torch>=2.11.0,<3.0.0",
    "torchvision>=0.26.0,<1.0.0",
]

# Define the index for downloading GPU PyTorch
[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

# If the "gpu" extra is requested, get PyTorch from the GPU index
[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", extra = "gpu" },
]
torchvision = [
  { index = "pytorch-cu128", extra = "gpu" },
]

# Ruff configuration
[tool.ruff]
target-version = "py311"
line-length = 120

# Include Jupyter Notebooks for Ruff
extend-include = ["*.ipynb"]

# Define which issues to flag
[tool.ruff.lint]
# E: Error, F: Pyflakes, I: Isort, UP: Pyupgrade, B: Bugbear
select = ["E", "F", "I", "UP", "B"]
fixable = ["ALL"]

# Jupyter Notebook specific settings
[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    # Allow imports not at the top of the file
    "E402",
    # Ignore line length violations (notebooks often have long strings/data)
    "E501",
]

# Force double quotes for Python strings
[tool.ruff.format]
quote-style = "double"

# Mypy configuration
[tool.mypy]
python_version = "3.11"
strict = true

# Explicitly exclude the notebooks directory from type checking
exclude = [
    "^build/",
    '^notebooks/',
]

# Standard stability settings
warn_unused_configs = true
